### ISSUE TITLE
Something wrong when running inference:Could not Initialise the network. Have you enterred the correct model path?

### ISSUE THREAD

**Issue by ltt-lv** [healyr4/Gaze-Tracking#1]
D:\Programs\Python\Python39\python.exe F:/Gaze-Tracking-Trackereyes-master/src/main.py -o results -it cam
F:\Gaze-Tracking-Trackereyes-master\src\data_evaluation.py:31: DeprecationWarning: invalid escape sequence \G
  path = 'F:\Gaze-Tracking-Trackereyes-master\calibration'
F:\Gaze-Tracking-Trackereyes-master\calibration
1920 1080
2021-07-01 10:37:02,816 [ERROR] Something wrong when running inference:Could not Initialise the network. Have you enterred the correct model path?
Traceback (most recent call last):
  File "F:\Gaze-Tracking-Trackereyes-master\src\inference.py", line 28, in _init_model
    self.model = self.core.read_network(model_structure, model_weights)
  File "ie_api.pyx", line 324, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 346, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: The support of IR v4 has been removed from the product. Please, convert the original model using the Model Optimizer which comes with this version of the OpenVINO to generate supported IR version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Gaze-Tracking-Trackereyes-master\src\main.py", line 83, in infer_on_stream
    face_detector = FaceDetector('models\\intel\\face-detection-adas-binary-0001\\FP32-INT1\\face-detection-adas-binary-0001')
  File "F:\Gaze-Tracking-Trackereyes-master\src\face_detection.py", line 19, in __init__
    self.network = Network(model_name, device, extensions)
  File "F:\Gaze-Tracking-Trackereyes-master\src\inference.py", line 17, in __init__
    self._init_model(model_name, device, extensions)
  File "F:\Gaze-Tracking-Trackereyes-master\src\inference.py", line 30, in _init_model
    raise ValueError("Could not Initialise the network. Have you enterred the correct model path?")
ValueError: Could not Initialise the network. Have you enterred the correct model path?

Process finished with exit code 0
We look forward to your reply!

**Comment by ltt-lv** [comment]
path = 'C:\\Users\healy\OneDrive - TCDUD.onmicrosoft.com\Desktop\Gaze-Estimation2\calibration
I don't know what path this path is.

**Comment by healyr4** [comment]
> path = 'C:\Users\healy\OneDrive - TCDUD.onmicrosoft.com\Desktop\Gaze-Estimation2\calibration
> I don't know what path this path is.

Thanks for catching that, I've updated the path now so it is correct.

> ValueError: Could not Initialise the network. Have you enterred the correct model path?
> face_detector = FaceDetector('models\intel\face-detection-adas-binary-0001\FP32-INT1\face-detection-adas-binary-0001')

The issue is with this path. It should be correct. I've even cloned the repo into a new directory on my machine and it's working. Can I ask are you using windows/mac/linux? That may be the issue.
